baseURL = "https://cv.whyelsetheyare.com/"
languageCode = "en-us"
theme = "almeida-cv"
title = "Nguyen Viet Tu - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#666"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
